"""
Mejoras pagas y gratuitas para sumar al jardín.
Tres tiers: free · under_10 · under_100 (USD).

Cada entrada se asocia a una zona ("frente", "fondo", "interior", "all").
`applies_to` lista códigos de planta (ej. "B-23") para chips clickeables que
abren el modal de detalle de la especie.
"""

IMPROVEMENTS = [
    # ============================================================
    # FRENTE (oeste — sol vespertino)
    # ============================================================
    {
        "id": "frente-grass-overseed",
        "zone": "frente",
        "tier": "under_10",
        "cost_usd": 8,
        "title": "Resembrar el césped del cantero",
        "category": "césped",
        "what": "Mezcla de semilla festuca + ryegrass anual shade-tolerant (1 kg cubre ~30 m²).",
        "why": "El frente tiene parches ralos bajo las fotinias. Una resiembra de otoño llena los claros antes del invierno y deja un colchón verde.",
        "how": "Rastrillar superficial para abrir el suelo, sembrar a voleo 30 g/m², tapar con 1 cm de compost fino, regar liviano 10 días seguidos.",
        "when": "Marzo–mayo (mejor) o agosto–septiembre.",
        "where_buy": "Vivero Antares · Casa Sasso · Mercado Libre — buscar 'mezcla resiembra sombra'.",
        "applies_to": [],
        "tags": ["césped", "otoño"],
    },
    {
        "id": "frente-iron-sulfate-fotinias",
        "zone": "frente",
        "tier": "under_10",
        "cost_usd": 5,
        "title": "Sulfato de hierro para fotinias amarillentas",
        "category": "nutrientes",
        "what": "Sulfato ferroso (FeSO₄), bolsa de 500 g.",
        "why": "Las fotinias F-1..F-6 muestran clorosis (hojas amarillas con nervios verdes) cuando el suelo es muy alcalino. El hierro recupera el rojo intenso del rebrote.",
        "how": "Disolver 5 g/L de agua y regar al pie 1 vez por mes durante 3 meses. No mojar follaje a pleno sol.",
        "when": "Primavera (septiembre–noviembre) cuando empieza el rebrote.",
        "where_buy": "Agroveterinarias · viveros grandes — pedir 'sulfato de hierro soluble'.",
        "applies_to": ["F-1", "F-2", "F-3", "F-4", "F-5", "F-6"],
        "tags": ["nutrientes", "fotinias"],
    },
    {
        "id": "frente-frost-cloth",
        "zone": "frente",
        "tier": "under_100",
        "cost_usd": 25,
        "title": "Malla anti-helada para rosales y jazmín",
        "category": "protección",
        "what": "Tela TNT agryl 17 g/m², rollo de 3×5 m.",
        "why": "El frente recibe heladas tardías al amanecer (junio–agosto). Cubrir rosales jóvenes y trepadoras tiernas evita quemado de yemas florales.",
        "how": "Cubrir las plantas las noches que pronostican < 2 °C. Retirar al sol del mediodía para no condensar humedad.",
        "when": "Junio–agosto, las 6–10 noches más frías del año.",
        "where_buy": "Casa Sasso · viveros grandes · Mercado Libre — 'tela antiheladas agryl 17'.",
        "applies_to": [],
        "tags": ["protección", "invierno"],
    },
    {
        "id": "frente-bark-mulch",
        "zone": "frente",
        "tier": "under_100",
        "cost_usd": 40,
        "title": "Mulch de corteza de pino para canteros",
        "category": "sustrato",
        "what": "Bolsa de 50 L de corteza de pino mediana (cubre ~2 m² a 3 cm).",
        "why": "Conserva humedad en verano (riego más espaciado), suprime malezas, y al descomponerse acidifica un poco el suelo — ideal para fotinias y abelia.",
        "how": "Capa de 3–5 cm alrededor del tronco dejando 5 cm de aire en el cuello. Renovar cada 18 meses.",
        "when": "Noviembre (antes del calor fuerte).",
        "where_buy": "Viveros · barracas de paisajismo.",
        "applies_to": ["F-5", "F-7"],
        "tags": ["sustrato", "verano"],
    },

    # ============================================================
    # FONDO (este — sol matinal)
    # ============================================================
    {
        "id": "fondo-citrus-fert",
        "zone": "fondo",
        "tier": "under_10",
        "cost_usd": 6,
        "title": "Fertilizante específico para cítricos",
        "category": "nutrientes",
        "what": "NPK 12-5-14 con micronutrientes (Mg, Fe, Zn), bolsa de 1 kg.",
        "why": "Los cítricos son ávidos de nitrógeno y muy susceptibles a clorosis. Un fertilizante balanceado les da hojas verde-oscuro y mejor cuaje de fruta.",
        "how": "30 g por planta repartido en 3 aplicaciones: agosto, noviembre, febrero. Espolvorear bajo la copa y regar.",
        "when": "3 veces al año (primavera, fin de primavera, verano).",
        "where_buy": "Agroveterinarias · viveros — pedir 'fertilizante cítricos'.",
        "applies_to": ["B-23", "B-24"],
        "tags": ["nutrientes", "frutal"],
    },
    {
        "id": "fondo-fruit-tree-fert",
        "zone": "fondo",
        "tier": "under_10",
        "cost_usd": 7,
        "title": "Abono para frutales de carozo y pepita",
        "category": "nutrientes",
        "what": "Fertilizante de invierno tipo 10-10-10 + materia orgánica, 2 kg.",
        "why": "Durazno y peral necesitan reservas para fructificación abundante. Una aplicación en pleno reposo invernal recarga reservas para la brotación.",
        "how": "200 g enterrados levemente en corona alrededor del tronco (radio de la copa). Regar después.",
        "when": "Julio (pleno invierno, antes de la brotación).",
        "where_buy": "Agroveterinarias.",
        "applies_to": ["B-30", "B-39"],
        "tags": ["nutrientes", "frutal", "invierno"],
    },
    {
        "id": "fondo-avocado-stake",
        "zone": "fondo",
        "tier": "under_10",
        "cost_usd": 9,
        "title": "Tutor reforzado para el palto",
        "category": "estructura",
        "what": "Tutor de bambú o caña tacuara de 2.5 m + atadura goma elástica.",
        "why": "El palto B-36 todavía es joven y el viento del este (sale el sol acá) lo mueve. Un tutor firme los primeros 2–3 años evita inclinación permanente.",
        "how": "Clavar el tutor 40 cm en suelo, a 10 cm del tronco. Atar en 8 con goma cada 60 cm — nunca cordel rígido (estrangula).",
        "when": "Cualquier época, mejor antes de los vientos de primavera (septiembre).",
        "where_buy": "Ferreterías · viveros · Mercado Libre.",
        "applies_to": ["B-36"],
        "tags": ["estructura"],
    },
    {
        "id": "fondo-drip-irrigation",
        "zone": "fondo",
        "tier": "under_100",
        "cost_usd": 60,
        "title": "Kit de riego por goteo para frutales",
        "category": "riego",
        "what": "Kit con 25 m de manguera, 10 goteros autocompensados, conectores y timer mecánico.",
        "why": "Los frutales del fondo (durazno, peral, palto, cítricos) producen mucho más con riego constante en verano. Goteo gasta 70% menos agua que aspersión.",
        "how": "Tender la manguera a 30 cm del tronco, 2 goteros por árbol grande, 30 min/día con timer. Tapar con mulch para que no se degrade el plástico.",
        "when": "Instalar en septiembre antes de la temporada seca.",
        "where_buy": "Casa Sasso · agroveterinarias · Sodimac.",
        "applies_to": ["B-23", "B-24", "B-30", "B-36", "B-39"],
        "tags": ["riego", "verano"],
    },

    # ============================================================
    # INTERIOR
    # ============================================================
    {
        "id": "interior-foliar-spray",
        "zone": "interior",
        "tier": "under_10",
        "cost_usd": 4,
        "title": "Spray foliar de agua + sales para tropicales",
        "category": "nutrientes",
        "what": "Pulverizador 1 L + fertilizante foliar líquido NPK 6-6-6, frasco 250 ml.",
        "why": "Helechos, aroides y plantas de interior agradecen humedad ambiente alta. El spray foliar suplementa nutrientes vía hoja y simula el ambiente tropical.",
        "how": "Diluir 2 ml/L y pulverizar el envés de la hoja una vez por semana en primavera–verano. Solo agua en otoño–invierno.",
        "when": "Septiembre–marzo, semanal.",
        "where_buy": "Viveros · supermercados con sección de jardín.",
        "applies_to": [],
        "tags": ["nutrientes", "interior"],
    },
    {
        "id": "interior-grow-light",
        "zone": "interior",
        "tier": "under_100",
        "cost_usd": 45,
        "title": "Panel LED full-spectrum para plantas",
        "category": "iluminación",
        "what": "Panel LED 30 W full-spectrum (rojo + azul + blanco), con timer USB.",
        "why": "En invierno los días son cortos y muchas tropicales pierden hojas por falta de luz. Un panel suplementa 6 h/día y mantiene el follaje.",
        "how": "Colgar a 40–60 cm de la planta. Encender 6 h/día (idealmente con timer 8:00–14:00).",
        "when": "Mayo–agosto (días más cortos).",
        "where_buy": "Mercado Libre · Amazon — buscar 'grow light LED full spectrum'.",
        "applies_to": [],
        "tags": ["iluminación", "invierno", "interior"],
    },
    {
        "id": "interior-aroid-mix",
        "zone": "interior",
        "tier": "under_10",
        "cost_usd": 9,
        "title": "Sustrato específico para aroides (Monstera, Philodendron)",
        "category": "sustrato",
        "what": "Mezcla con corteza de pino, perlita, fibra de coco y carbón vegetal — 5 L.",
        "why": "Las aroides se pudren en tierra común. El sustrato chunky drena rápido y deja oxígeno en la raíz aérea, evitando el podrido de cuello.",
        "how": "Trasplantar a maceta solo 2 cm más ancha. Rellenar con la mezcla, regar abundante una sola vez y dejar secar 5 días.",
        "when": "Septiembre–octubre (inicio de crecimiento activo).",
        "where_buy": "Viveros especializados · Mercado Libre — 'sustrato aroides'.",
        "applies_to": [],
        "tags": ["sustrato", "interior"],
    },

    # ============================================================
    # TODO / ALL (transversales a cualquier zona)
    # ============================================================
    {
        "id": "all-compost-bin",
        "zone": "all",
        "tier": "free",
        "cost_usd": 0,
        "title": "Compostera casera con palets reciclados",
        "category": "sustrato",
        "what": "4 palets de descarte + alambre o tornillos.",
        "why": "Fertilizante gratis y constante para todo el jardín. Cierra el ciclo de los restos verdes (poda, césped cortado, restos de cocina vegetales).",
        "how": "Armar caja de ~1×1×1 m con palets en rincón sombrío del fondo. Alternar capas verdes (césped, restos cocina) y secas (hojarasca, ramitas). Voltear cada 3 semanas. Listo en 4–6 meses.",
        "when": "Cualquier época. Empieza ya.",
        "where_buy": "Gratis — palets de descarte de barracas/supermercados.",
        "applies_to": [],
        "tags": ["sustrato", "compost"],
    },
    {
        "id": "all-rainwater-bucket",
        "zone": "all",
        "tier": "free",
        "cost_usd": 0,
        "title": "Recolección de agua de lluvia con baldes",
        "category": "riego",
        "what": "Baldes/tachos que ya tengas (mínimo 2 × 20 L).",
        "why": "El agua de lluvia es ácida (pH ~6) y sin cloro — ideal para hortensias, helechos, camelias y plantas de interior que sufren con agua de canilla.",
        "how": "Poner los tachos bajo bajadas de canaleta. Tapar con malla mosquitera para no juntar larvas. Usar dentro de 2 semanas.",
        "when": "Todo el año — abril–octubre es cuando más llueve en Montevideo.",
        "where_buy": "Gratis — material que ya tenés.",
        "applies_to": [],
        "tags": ["riego"],
    },
    {
        "id": "all-pruning-shears",
        "zone": "all",
        "tier": "under_100",
        "cost_usd": 35,
        "title": "Tijera de podar bypass Fiskars (o equivalente)",
        "category": "herramientas",
        "what": "Tijera de podar profesional bypass, hoja de acero al carbono.",
        "why": "Una tijera afilada hace cortes limpios que cicatrizan rápido. Las baratas aplastan el tallo y dejan entradas para hongos. Una buena dura 20 años.",
        "how": "Limpiar con alcohol entre planta y planta (evita contagio de virus). Afilar 2× al año con piedra fina.",
        "when": "Comprar antes de la temporada de poda (mayo–agosto).",
        "where_buy": "Sodimac · Mercado Libre · ferreterías grandes.",
        "applies_to": [],
        "tags": ["herramientas"],
    },
    {
        "id": "all-soil-test-kit",
        "zone": "all",
        "tier": "under_10",
        "cost_usd": 8,
        "title": "Kit de medición de pH y humedad del suelo",
        "category": "herramientas",
        "what": "Medidor analógico 3 en 1 (pH, humedad, luz), sin batería.",
        "why": "Antes de invertir en enmiendas, saber el pH real evita errores. Las hortensias quieren pH ácido (5–6), los frutales neutro (6.5–7), las aromáticas mediterráneas alcalino (7+).",
        "how": "Clavar el sensor 10 cm en suelo húmedo. Esperar 1 minuto. Anotar lectura por zona.",
        "when": "Cualquier época, mejor 2 horas después de regar.",
        "where_buy": "Mercado Libre · viveros — buscar 'medidor pH suelo 3 en 1'.",
        "applies_to": [],
        "tags": ["herramientas"],
    },
]
